version: '3.8'

services:
  game_db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: dongt
      POSTGRES_DB: gomoku_v1
      POSTGRES_USER: dongt
    container_name: game_db_v1
    ports:
      - '5435:5432'
    volumes:
      - game_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - game_db

volumes:
  game_db_data:
