export enum EMetadataKeys {
  IS_PUBLIC = 'isPublic',
}

export enum EProvide {
  USER_REPOSITORY = 'USER_REPOSITORY',
  DATA_SOURCE = 'DATA_SOURCE',
}

export const PAGE_SIZE = 25;

export enum EConfigKeys {
  // JWT
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_RESET_PASSWORD_EXPIRES_IN = 'JWT_RESET_PASSWORD_EXPIRES_IN',
  JWT_ACTIVATION_EXPIRES_IN = 'JWT_ACTIVATION_EXPIRES_IN',
  // MAILER
  MAILER_HOST = 'MAILER_HOST',
  MAILER_PORT = 'MAILER_PORT',
  MAILER_USERNAME = 'MAILER_USERNAME',
  MAILER_PASSWORD = 'MAILER_PASSWORD',
  MAILER_FROM = 'MAILER_FROM',
  // APP
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  CLIENT_URL = 'CLIENT_URL',
  CLIENT_RESET_PASSWORD_URL = 'CLIENT_RESET_PASSWORD_URL',
  // DATABASE
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  DB_SYNC = 'DB_SYNC',
}
